version: '2.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: python-web
    container_name: python-web
    volumes:
      - ./:/home/web/app
    command: bash -c "cd app && python main.py makemigrations && python main.py migrate && python main.py runserver"
    environment:
      - app_env=local
    ports:
      - "8000:8000"
    expose:
      - "8000"